all: test_model.dll
	#Comment here preserves the prior tab
test_model.dll: test_model.cpp
	Rscript --vanilla -e "TMB::compile(file='test_model.cpp', flags='-O0 -g', framework = 'TMBad')"
clean:
	rm -rf *o